export const TERM_DEFINITIONS = {
  ufcf: "Unlevered Free Cash Flow: cash generated by operations after tax and reinvestment, but before interest or debt payments. It belongs to both lenders and shareholders.",
  wacc: "Weighted Average Cost of Capital: the annual return required by the company’s debt and equity investors. A higher WACC lowers today’s value of future cash flows.",
  ebit: "Earnings Before Interest and Taxes: operating profit before financing costs and income taxes.",
  nopat: "Net Operating Profit After Tax: EBIT after normalized cash taxes, while still excluding interest and other financing costs.",
  ebitda: "Earnings Before Interest, Taxes, Depreciation, and Amortization: an operating earnings measure before non-cash D&A. It is not the same as free cash flow.",
  da: "Depreciation and amortization: non-cash accounting charges that spread the cost of long-lived assets and acquired intangibles over time.",
  capex: "Capital expenditures: cash spent on long-lived assets such as equipment, facilities, servers, or infrastructure.",
  nwc: "Net working capital: short-term operating assets minus short-term operating liabilities. Growth can consume cash when receivables or inventory rise faster than payables.",
  pv: "Present value: what a future cash flow is worth today after discounting it for time and risk.",
  terminalValue: "Terminal value: the estimated value of all cash flows after the explicit five-year forecast. It often represents a large share of a DCF.",
  terminalRoic: "Terminal return on invested capital: the return assumed on new long-run investment. Perpetual reinvestment equals growth divided by terminal ROIC. Setting terminal ROIC equal to WACC assumes new investment creates no excess value in perpetuity.",
  yearFive: "Year 5 is the point exactly five years after the valuation date. When that date falls between two fiscal year-ends, the model blends the fifth and sixth forecast periods. That blended UFCF or EBITDA is used to calculate terminal value.",
  perpetualGrowth: "Perpetual growth method: assumes cash flow grows at a stable rate forever after Year 5. The growth rate must stay below WACC.",
  exitMultiple: "Exit multiple method: estimates the company’s Year 5 value by multiplying Year 5 EBITDA by a market valuation multiple.",
  enterpriseValue: "Enterprise value: the value of the operating business available to both lenders and shareholders, before adding cash and subtracting debt.",
  equityValue: "Equity value: the portion belonging to common shareholders after adding available cash and subtracting debt and other senior claims.",
  dilutedShares: "Diluted shares: the share count including potential dilution from options, restricted stock, convertibles, and similar securities.",
  discountFactor: "Discount factor: the multiplier that converts a future cash flow into today’s dollars using WACC and the number of years away.",
  revenueGrowth: "Starting revenue growth: the expected percentage increase in sales during Year 1. The model gradually fades this rate toward the long-run terminal growth rate.",
  ebitMargin: "Target EBIT margin: the percentage of revenue expected to remain as operating profit before interest and taxes by Year 5.",
  taxRate: "Tax rate: the normalized cash tax percentage applied to positive operating profit. It should reflect a sustainable rate rather than a one-time tax benefit or charge.",
  terminalGrowth: "Terminal growth: the annual rate the company is assumed to grow forever after Year 5. It must remain below WACC, should generally not exceed the same-currency risk-free rate, and should resemble mature long-run nominal growth.",
  marketPrice: "Market price: the current or reference share price used only to calculate potential upside or downside. Changing it does not change the DCF’s intrinsic value.",
  cash: "Cash: cash considered available to shareholders. It is added to enterprise value when calculating equity value.",
  fundedDebt: "Funded debt: interest-bearing borrowings that must be repaid. It is subtracted from enterprise value before calculating equity value.",
  riskFreeRate: "Risk-free rate: the return investors could earn with minimal default risk, commonly approximated with a long-term U.S. Treasury yield. It forms the starting point for required returns.",
  beta: "Beta: an estimate of how sensitive the stock has been to broad market movements. When sufficient history exists, this site adjusts the raw regression beta one-third toward 1.0 to reduce sampling noise. A beta of 1.0 moves roughly with the market.",
  equityRiskPremium: "Equity risk premium: the additional annual return investors require for owning stocks instead of a risk-free asset.",
  costOfEquity: "Cost of equity: the return shareholders require for taking the company’s risk. This reference uses risk-free rate + beta × equity risk premium.",
  equityWeight: "Equity / capital: the percentage of the company’s financing represented by equity market value. It determines how much the cost of equity influences WACC.",
  preTaxCostOfDebt: "Pre-tax cost of debt: the estimated interest rate the company pays or would pay on borrowings before the tax benefit of deductible interest.",
  debtWeight: "Debt / capital: the percentage of financing represented by funded debt. It determines how much the after-tax cost of debt influences WACC.",
  companySpecificPremium: "Company-specific premium: a visible judgment adjustment added after the standard WACC formula. It starts at 0% when beta history is sufficient. If beta history is insufficient, the automatic starting value only fills the gap to the disclosed industry WACC; replace it with a bottom-up beta when possible and avoid double counting risk in cash flows.",
} as const;

export type DefinedTermKey = keyof typeof TERM_DEFINITIONS;

export function DefinedTerm({ term, children }: { term: DefinedTermKey; children: string }) {
  const definition = TERM_DEFINITIONS[term];
  return <span className="defined-term" tabIndex={0} title={definition} data-definition={definition}>{children}</span>;
}

const DCF_ROW_TERMS: Record<string, DefinedTermKey> = {
  EBIT: "ebit",
  "Operating Income": "ebit",
  NOPAT: "nopat",
  "D&A / revenue": "da",
  "D&A / Revenue": "da",
  "Depreciation & amortization": "da",
  "Plus: Depreciation & Amortization": "da",
  "Capex / revenue": "capex",
  "Capex / Revenue": "capex",
  "Less: Capital Expenditure": "capex",
  "Capital expenditures": "capex",
  "Change in net working capital": "nwc",
  "Less: Changes in Net Working Capital": "nwc",
  "Unlevered Free Cash Flow (UFCF)": "ufcf",
  "Free Cash Flow": "ufcf",
  "Discount factor": "discountFactor",
  "Discount Factor": "discountFactor",
  "PV of UFCF": "pv",
  "Present Value of Free Cash Flow": "pv",
  "Perpetual-growth terminal value": "terminalValue",
  "PV of perpetual terminal value": "pv",
  "Exit-multiple terminal value": "terminalValue",
  "PV of exit-multiple terminal value": "pv",
};

export function DcfRowLabel({ label }: { label: string }) {
  const term = DCF_ROW_TERMS[label];
  return term ? <DefinedTerm term={term}>{label}</DefinedTerm> : label;
}
